<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11078" started-at="2020-01-17T21:25:01 CST" finished-at="2020-01-17T21:25:13 CST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11078" started-at="2020-01-17T21:25:01 CST" finished-at="2020-01-17T21:25:13 CST">
      <class name="com.class03.HW">
        <test-method status="PASS" signature="Open()[pri:0, instance:com.class03.HW@369f73a2]" name="Open" is-config="true" duration-ms="4293" started-at="2020-01-17T21:25:02 CST" finished-at="2020-01-17T21:25:06 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Open -->
        <test-method status="PASS" signature="AddEmp()[pri:0, instance:com.class03.HW@369f73a2]" name="AddEmp" duration-ms="6716" started-at="2020-01-17T21:25:06 CST" finished-at="2020-01-17T21:25:13 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddEmp -->
        <test-method status="FAIL" signature="login(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.class03.HW@369f73a2]" name="login" duration-ms="0" started-at="2020-01-17T21:25:13 CST" data-provider="getData" finished-at="2020-01-17T21:25:13 CST">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.class03.HW.login(java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : getData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.class03.HW.login(java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : getData
at org.testng.internal.Parameters.findDataProvider(Parameters.java:580)
at org.testng.internal.Parameters.handleParameters(Parameters.java:795)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- com.class03.HW -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
